### ISSUE TITLE
Know your Handle 

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/intro-february-2016#104]
### Please Tell Me this Information
- [ ] Handle Name
- [ ] Your Hometown

**Comment by crichID** [comment]
- @crichID
- Fuquay Varina, NC

**Comment by swinton** [comment]
- [x] I am @swinton
- [x] I live in [Franklin, TN](https://goo.gl/maps/zr33SbD9eDP2)

![dance](https://cloud.githubusercontent.com/assets/27806/13157037/420413e8-d64b-11e5-90e1-4b8ae0c83d90.gif)

**Comment by githubteacher** [comment]
@crichid ... Can you please also let me know what Country you are located?

**Comment by crichID** [comment]
@githubteacher I am in the USA
